name: Setup jank - The native Clojure dialect hosted on LLVM with seamless C++ interop.
description: Set up your Github actions runner with jank.
author: djblue

runs:
  using: composite
  steps:
    - name: Setup jank on Linux
      if: runner.os == 'Linux'
      run: |
        sudo "$GITHUB_ACTION_PATH"/linux.sh
      shell: sh
    - name: Setup jank on macOS
      if: runner.os == 'macOS'
      run: |
        "$GITHUB_ACTION_PATH"/macos.sh
      shell: sh
    - name: Setup jank on Windows
      if: runner.os == 'Windows'
      run: |
        Write-Error "Sorry, setup-jank is not currently available on windows."
        Exit 1
      shell: pwsh


branding:
  icon: 'bold'
  color: 'green'
